service: serverless-simple-http-endpoint

provider:
  name: aws
  runtime: nodejs8.10

functions:
  currentTime:
    handler: handler.endpoint
    events:
      - http:
          path: ping
          method: get
